/* Autogenerated by png2wx.pl on Mon Aug 27 13:51:44 2018 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

#include "ocpn_plugin.h"

#include <wx/filename.h>
#include <wx/mstream.h>


extern void initialize_images(void);

extern wxBitmap *_img_pypilot_blue;
extern wxBitmap *_img_pypilot_cyan;
extern wxBitmap *_img_pypilot_green;
extern wxBitmap *_img_pypilot_grey;
extern wxBitmap *_img_pypilot_red;
extern wxBitmap *_img_pypilot_yellow;


#ifdef PLUGIN_USE_SVG
extern wxString _svg_pypilot;
extern wxString _svg_pypilot_rollover;
extern wxString _svg_pypilot_toggled;
#endif


#endif /* ICONS_H */
