/* Autogenerated by png2wx.pl on Mon Dec 25 19:54:06 2017 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_pypilot;

#endif /* ICONS_H */
