#define PLUGIN_NAME pypilot_pi
#define PLUGIN_CATALOG_NAME wxS("opencpn-pypilot_pi")
#define PLUGIN_VERSION_MAJOR 0
#define PLUGIN_VERSION_MINOR 2
#define PLUGIN_VERSION_PATCH 000
#define PLUGIN_VERSION_DATE "2018-1-10"
